abstract final class RouteNames {
  static const bootstrap = 'bootstrap';
  static const login = 'login';
  static const register = 'register';
  static const onboarding = 'onboarding';
  static const authenticated = 'authenticated';
  static const home = 'home';
  static const data = 'data';
  static const messages = 'messages';
  static const profile = 'profile';
  static const search = 'search';
  static const publish = 'publish';
  static const contentDetail = 'content-detail';
  static const matchDetail = 'match-detail';
  static const teamDetail = 'team-detail';
  static const playerDetail = 'player-detail';
  static const publishPost = 'publish-post';
  static const publishArticle = 'publish-article';
  static const editArticle = 'edit-article';
  static const publicUser = 'public-user';
}
